name: lint

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install rust
        run: rustup toolchain install nightly
      - name: Check
        run: cargo check --all --all-targets

  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install rust
        run: rustup toolchain install nightly
      - name: Install rustfmt
        run: rustup component add rustfmt
      - name: Format
        run: cargo fmt --all -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install rust
        run: rustup toolchain install nightly
      - name: Install clippy
        run: rustup component add clippy
      - name: Clippy
        run: cargo clippy --all --all-targets -- -D warnings

  rustdoc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install rust
        run: rustup toolchain install nightly
      - name: Rustdoc
        run: cargo doc --all --no-deps

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install rust
        run: rustup toolchain install nightly
      - name: Test
        run: cargo test --all --all-targets
